apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikipedia-chatbot-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: wikipedia-chatbot.inf326.cl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wikipedia-chatbot-service
            port:
              number: 9001
  - host: wikipedia-chatbot-134-199-176-197.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wikipedia-chatbot-service
            port:
              number: 9001
